package int_group6.mytunesintgroup6.be;

public class Playlist {

    private int id;
    private String name;

    // Constructor used when loading a playlist from the database (ID is already known)
    public Playlist(int id, String name) {
        this.id = id;
        this.name = name;
    }

    // Constructor used when creating a new playlist from the GUI (ID will be generated by the DB)
    public Playlist(String name) {
        this(-1, name);
    }

    public int getId() {
        return id;
    }

    // Setter available in case the ID needs to be assigned after an INSERT
    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    // Allows renaming the playlist
    public void setName(String name) {
        this.name = name;
    }

    // Useful for debugging or when displaying playlists in UI components (like ListView)
    @Override
    public String toString() {
        return name;
    }
}
